/* *******************  Prepared by Saeed, 11/05/15, ********************/ 
/****************** to find the Trans,BU,apeals,Interac, of donations  ******************/
/*****************************************************************************************/

Print ('Creating Table Bio')
IF OBJECT_ID('tempdb..#Bio') IS NOT NULL DROP TABLE #Bio  --Remove dbo here 
   
Select CONSTITUENTLOOKUPID,CONSTITUENTDIMID,[AGE],[TITLE],CONSTITUENT.[GENDER],CONSTITUENT.[DONOTMAIL]
      ,CONSTITUENT.[GIVESANONYMOUSLY]
      ,CONSTITUENT.[ISACTIVE]
      ,CONSTITUENT.[ISCONSTITUENT]
      ,CONSTITUENT.[ISDECEASED]
      ,CONSTITUENT.[ISGROUP]
      ,CONSTITUENT.[ISORGANIZATION]
      ,CONSTITUENT.[ISNETCOMMUNITYMEMBER]
	  ,CONSTITUENT.[MARITALSTATUS]
      ,CONSTITUENT.[ISACTIVEBOARDMEMBER]
      ,CONSTITUENT.[ISACTIVECOMMITTEE]
      ,CONSTITUENT.[ISACTIVEFUNDRAISER]
      ,CONSTITUENT.[ISACTIVEPROSPECT]
      ,CONSTITUENT.[ISACTIVESTAFF]
      ,CONSTITUENT.[ISACTIVESPONSOR]
      ,CONSTITUENT.[ISACTIVEVOLUNTEER]
INTO #Bio
from [ECSKF_RPT_BBDW].[BBDW].[DIM_CONSTITUENT] AS CONSTITUENT
inner join  [ECSKF_RPT_BBDW].[dbo].[SKF_RPT_ConstituentType_EXT] AS CONSTITUENT_TYPE
on CONSTITUENT_TYPE.[CONSTITUENTSYSTEMID]=CONSTITUENT.[CONSTITUENTSYSTEMID]
where CONSTITUENT_TYPE.CONSTITUENTTYPE='Individual'

update #Bio set gender='Female' where Title  in ('Ms.','Mrs.','Miss','Dr. & Mrs.','Madam','Madame','Sister') and (gender='Unknown' or gender is null)
update #Bio set gender='Male' where Title  in ('Mr.','Brother','Father') and (gender='Unknown' or gender is null)

--select count(*) from [ECSKF_RPT_BBDW].[BBDW].[DIM_CONSTITUENT] as CONSTITUENT
--inner join  [ECSKF_RPT_BBDW].[dbo].[SKF_RPT_ConstituentType_EXT] AS CONSTITUENT_TYPE
--on CONSTITUENT_TYPE.[CONSTITUENTSYSTEMID]=CONSTITUENT.[CONSTITUENTSYSTEMID]
--where CONSTITUENT_TYPE.CONSTITUENTTYPE='Individual'
--select count(*) from #Bio
--select top 100 * from #Bio
--select distinct [CONSTITUENTADDRESSTYPE] from #Bio
--select  * from #Bio where  CONSTITUENTLOOKUPID='70434'
-- select  maritalstatus, count(maritalstatus) from #Bio group by maritalstatus
-----Address---------------------------------------------------------------

IF OBJECT_ID('tempdb..#CAN_DATA') IS NOT NULL  DROP TABLE #CAN_DATA;
WITH CTE
AS
(
      SELECT LEFT(CANADA.PostalCode,3) + ' ' + RIGHT(CANADA.PostalCode,3) AS POST_CODE, CANADA.Latitude, CANADA.Longitude
                        , ROW_NUMBER() OVER (PARTITION BY LEFT(CANADA.PostalCode,3) + ' ' + RIGHT(CANADA.PostalCode,3) ORDER BY CANADA.Latitude ) AS FIRST_ROW
                  FROM [ConversionMapping].dbo.[CanData] AS CANADA 
) SELECT POST_CODE,     Latitude,Longitude
      INTO #CAN_DATA    
      FROM  CTE
      WHERE       FIRST_ROW = 1;


IF OBJECT_ID('tempdb..#AddDet') IS NOT NULL DROP TABLE #AddDet  --Remove dbo here 
select *  
into #AddDet
from 
(
select CONSTITUENT.CONSTITUENTDIMID
	,CONSTITUENT.CONSTITUENTLOOKUPID
	,CONSTITUENT.[PRIMARYADDRESSCITY]
    ,CONSTITUENT.[PRIMARYADDRESSSTATE]
	,LEFT(CONSTITUENT.PRIMARYADDRESSPOSTCODE,3) as FSA
	, #CAN_DATA.Longitude
	,#CAN_DATA.Latitude
	, ADD_TYPE.CONSTITUENTADDRESSTYPE
	, ADD_DETAILS.ISCONFIDENTIAL

from  [ECSKF_RPT_BBDW].[BBDW].[DIM_CONSTITUENT]  as CONSTITUENT 
inner join [ECSKF_RPT_BBDW].[BBDW].[FACT_CONSTITUENTADDRESS]  as b
on CONSTITUENT.CONSTITUENTDIMID=b.CONSTITUENTDIMID
inner join [ECSKF_RPT_BBDW].[BBDW].[DIM_CONSTITUENTADDRESSTYPE] as ADD_TYPE
on b.CONSTITUENTADDRESSTYPEDIMID=ADD_TYPE.CONSTITUENTADDRESSTYPEDIMID
left outer join [ECSKF_RPT_BBDW].[BBDW].[DIM_CONSTITUENTADDRESSFLAG] as ADD_DETAILS
on ADD_DETAILS.[CONSTITUENTADDRESSFLAGDIMID] = CONSTITUENT.[CONSTITUENTADDRESSFLAGDIMID]
left outer join #CAN_DATA
on CONSTITUENT.PRIMARYADDRESSPOSTCODE=#CAN_DATA.POST_CODE
) as SRC
Pivot
(
count(CONSTITUENTADDRESSTYPE)
FOR CONSTITUENTADDRESSTYPE IN (Home, Business)
)as pivot_table
--select * from #AddDet
--select distinct(AFFLUENCEINDICATORNUMBER) from SKF_RPT_WealthAndRatings_EXT
--select * from [ECSKF_RPT_BBDW].[BBDW].[FACT_CONSTITUENTADDRESS] where CONSTITUENTDIMID='683601'
--select * from [dbo].[SKF_DM_ConstituentAddress_EXT] where CONSTITUENTID='E5E4D1C1-700A-4DC9-B12F-FC2B411D01D3'
-- select count(*),count(distinct CONSTITUENTDIMID) from #AddDet
-- select * from #AddDet where CONSTITUENTLOOKUPID='174572'
---Affluency-----------------------------------------------------------------
Print ('Creating Table AFF')
IF OBJECT_ID('tempdb..#AFF') IS NOT NULL DROP TABLE #AFF ; --Remove dbo here 
   
Select CONSTITUENTLOOKUPID,CONSTITUENTDIMID
	 ,AFF.AFFLUENCEINDICATORNUMBER
	 ,AFF.AFFLUENCEINDICATORASSETS
	 ,AFF.BIOGRAPHICALNUMBER
	 ,AFF.BUSINESSOWNERSHIPASSETS
	 ,AFF.BUSINESSOWNERSHIPNUMBER
	 ,AFF.NONPROFITAFFILIATIONNUMBER
	 ,AFF.PHILANTHROPICGIFTNUMBER
	 ,AFF.REALESTATENUMBER
INTO #AFF
from [ECSKF_RPT_BBDW].[BBDW].[DIM_CONSTITUENT] AS CONSTITUENT
left outer join [ECSKF_RPT_BBDW].[dbo].SKF_RPT_WealthAndRatings_EXT as AFF
on AFF.ConstituentSystemID=CONSTITUENT.CONSTITUENTSYSTEMID

---------------------------------------------------------------------
Print ('Creating Table Intr')
IF OBJECT_ID('tempdb..#intr') IS NOT NULL DROP TABLE #intr  --Remove dbo here 

Select CONSTITUENTLOOKUPID, max(INTER.[INTEREST]) as Interest
INTO #intr
from #Bio AS CONSTITUENT
left outer join [ECSKF_RPT_BBDW].[BBDW].[DIM_CONSTITUENTINTEREST] as INTER
on INTER.CONSTITUENTDIMID=CONSTITUENT.CONSTITUENTDIMID
group by CONSTITUENTLOOKUPID

--select count(*),count(distinct CONSTITUENTLOOKUPID) from #intr

-----------------------------------------------------------------------
Print ('Creating Table APPEAL')
IF OBJECT_ID('tempdb..#APPEAL') IS NOT NULL DROP TABLE #APPEAL  --Remove dbo here 
SELECT CONS_APPEAL.[CONSTITUENTDIMID]
	  ,count(*) as APEAL_COUNT,
	  sum(case when APPEAL.APPEALCATEGORY='Lottery' then 1 else 0 end) as APEAL_COUNT_lotry,
	  sum(case when APPEAL.APPEALCATEGORY='General Donations' then 1 else 0 end) as APEAL_COUNT_GenDon,
	  sum(case when APPEAL.APPEALCATEGORY='Door to Door' then 1 else 0 end) as APEAL_COUNT_DTD,
	  sum(case when APPEAL.APPEALCATEGORY='Corporate Partnerships' then 1 else 0 end) as APEAL_COUNT_CP,
	  sum(case when APPEAL.APPEALCATEGORY='Direct Mail' then 1 else 0 end) as APEAL_COUNT_DM
INTO #APPEAL
  FROM [ECSKF_RPT_BBDW].[BBDW].[FACT_CONSTITUENTAPPEAL] CONS_APPEAL
  inner join [ECSKF_RPT_BBDW].[BBDW].[DIM_APPEAL] APPEAL
  on CONS_APPEAL.APPEALDIMID=APPEAL.APPEALDIMID
  group by CONS_APPEAL.[CONSTITUENTDIMID]
--select * from 	#APPEAL  where #APPEAL.CONSTITUENTDIMID='820'
------------------------------------------------------------------------------
Print ('Creating Table REV')
IF OBJECT_ID('tempdb..#REV') IS NOT NULL DROP TABLE #REV  --Remove dbo here 
SELECT min(CONVERT(DATE,REVENUE.FINANCIALTRANSACTIONDATE)) AS FIRST_REV_DATE,
	max(CONVERT(DATE,REVENUE.FINANCIALTRANSACTIONDATE)) AS LAST_REV_DATE,
	CO.CONSTITUENTLOOKUPID, 
	CODES.REVENUETRANSACTIONTYPE AS TRAN_TYPE 
	, CODES.REVENUEAPPLICATION AS APPLICATION_TYPE
    ,sum(REVENUE.FINANCIALTRANSACTIONLINEITEMAMOUNT) AS SUM_AMOUNT, '--------' as REV_TYPE
	,count(CONSTITUENTLOOKUPID) as GIFT_COUNT
     INTO #REV
     FROM  [ECSKF_RPT_BBDW].[BBDW].FACT_FINANCIALTRANSACTIONLINEITEM AS REVENUE
                  INNER JOIN  [ECSKF_RPT_BBDW].[BBDW].DIM_CONSTITUENT AS CO
                        ON CO.CONSTITUENTDIMID = REVENUE.CONSTITUENTDIMID
                  INNER JOIN  [ECSKF_RPT_BBDW].[BBDW].DIM_REVENUECODE AS CODES
                        ON CODES.REVENUECODEDIMID = REVENUE.REVENUECODEDIMID 
where 
(codes.REVENUETRANSACTIONTYPECODE = 0 and CODES.REVENUEAPPLICATIONCODE = 0) --Donation
or (codes.REVENUETRANSACTIONTYPECODE = 0  and CODES.REVENUEAPPLICATIONCODE = 3)--payment RG
or (codes.REVENUETRANSACTIONTYPECODE = 0  and CODES.REVENUEAPPLICATIONCODE = 2) --payment Pledge
or  (codes.REVENUETRANSACTIONTYPECODE = 2 )  --RG
or  (codes.REVENUETRANSACTIONTYPECODE = 1 )  --Pledge
or (codes.REVENUETRANSACTIONTYPECODE = 4)   --planned gift
group by CO.CONSTITUENTLOOKUPID,CODES.REVENUETRANSACTIONTYPE,CODES.REVENUEAPPLICATION

update #REV set REV_TYPE='P_DON' where TRAN_TYPE='Payment' and APPLICATION_TYPE='Donation'
update #REV set REV_TYPE='P_RG' where TRAN_TYPE='Payment' and APPLICATION_TYPE='Recurring gift'
update #REV set REV_TYPE='P_PLG' where TRAN_TYPE='Payment' and APPLICATION_TYPE='Pledge'
update #REV set REV_TYPE='H_RG' where TRAN_TYPE='Recurring gift' and APPLICATION_TYPE='Donation'
update #REV set REV_TYPE='H_PLG' where TRAN_TYPE='Pledge' and APPLICATION_TYPE='Donation'
update #REV set REV_TYPE='H_PG' where TRAN_TYPE='Planned gift' and APPLICATION_TYPE='Donation'
--select * from #REV where CONSTITUENTLOOKUPID='70434'
------
IF OBJECT_ID('tempdb..#REVEN1') IS NOT NULL DROP TABLE #REVEN1  --Remove dbo here 
select *,0 as 'T_REV'
into #REVEN1
from  (select CONSTITUENTLOOKUPID,REV_TYPE, sum_amount  from #REV ) as sourcetable
PIVOT 
(
 max(sum_amount)
FOR REV_TYPE IN (P_DON,P_RG,P_PLG,H_RG,H_PLG,H_PG)
) as pivot_table

update #REVEN1 set T_REV=(isnull(P_DON,0) + isnull(P_RG,0)  + isnull(P_PLG,0))

--select * from #REVEN where CONSTITUENTLOOKUPID='70434'

-------
IF OBJECT_ID('tempdb..#REVEN2') IS NOT NULL DROP TABLE #REVEN2  --Remove dbo here 
select CONSTITUENTLOOKUPID,min(FIRST_REV_DATE) as FIRST_REV_DATE, max(LAST_REV_DATE) as LAST_REV_DATE
	, YEAR(max(LAST_REV_DATE))-YEAR (min(FIRST_REV_DATE)) as PAYLENGTH
	 , sum(GIFT_COUNT) GFT_TCOUNT
into #REVEN2
from  #REV
group by CONSTITUENTLOOKUPID

--select * from #REVEN where CONSTITUENTLOOKUPID='70434'
-----Consistency----------------------------------------------------------------------
Print ('Creating Table CONSISTENCY')
IF OBJECT_ID('tempdb..#CONSTITUENCY') IS NOT NULL DROP TABLE #CONSTITUENCY ;

WITH CTE AS 
(
SELECT  CONSTITUENTS.CONSTITUENTDIMID, CONSTITUENTS.CONSTITUENTLOOKUPID
      ,CASE WHEN CONSTITUENCY.CONSTITUENCYDIMID = 16 THEN 1 ELSE 0 END AS [IsFormerTrustee]
      ,CASE WHEN CONSTITUENCY.CONSTITUENCYDIMID = 28 THEN 1 ELSE 0 END AS [IsTrustee]
      ,CASE WHEN CONSTITUENCY.CONSTITUENCYDIMID = 6 THEN 1 ELSE 0 END AS [IsChairsCouncil]
      ,CASE WHEN CONSTITUENCY.CONSTITUENCYDIMID = 46 THEN 1 ELSE 0 END AS [IsParentofPatient]
      ,CASE WHEN CONSTITUENCY.CONSTITUENCYDIMID = 47 THEN 1 ELSE 0 END AS [IsGrandparentOfPatient]
      ,CASE WHEN CONSTITUENCY.CONSTITUENCYDIMID = 48 THEN 1 ELSE 0 END AS [IsFriendFamilyOfPatient]
      ,CASE WHEN CONSTITUENCY.CONSTITUENCY LIKE '%Committee%' THEN 1 ELSE 0 END AS [IsCommiteeMember]      
      ,CASE WHEN CONSTITUENCY.CONSTITUENCYDIMID = 26 THEN 1 ELSE 0 END AS [IsCampaignCabinet]
      ,CONSTITUENCIES.FROMDATE
      ,ROW_NUMBER() OVER (PARTITION BY CONSTITUENTS.CONSTITUENTDIMID, CONSTITUENTS.CONSTITUENTLOOKUPID ORDER BY CONSTITUENCIES.FROMDATE DESC) AS ROWNUMBER
      FROM  [ECSKF_RPT_BBDW].[BBDW].DIM_CONSTITUENT AS CONSTITUENTS
            INNER JOIN  [ECSKF_RPT_BBDW].[BBDW].FACT_CONSTITUENCY AS CONSTITUENCIES
                  ON CONSTITUENTS.CONSTITUENTDIMID = CONSTITUENCIES.CONSTITUENTDIMID
            INNER JOIN  [ECSKF_RPT_BBDW].[BBDW].DIM_CONSTITUENCY AS CONSTITUENCY
                  ON    CONSTITUENCY.CONSTITUENCYDIMID = CONSTITUENCIES.CONSTITUENCYDIMID
            INNER JOIN [ECSKF_RPT_BBDW].dbo.SKF_RPT_ConstituentType_EXT AS CONSTITUENTTYPE
                  ON CONSTITUENTS.CONSTITUENTSYSTEMID = CONSTITUENTTYPE.ConstituentSystemId
      WHERE       CONSTITUENTTYPE = 'Individual'
)
SELECT CONSTITUENTDIMID,CONSTITUENTLOOKUPID, [IsFormerTrustee],[IsTrustee],[IsChairsCouncil],[IsParentofPatient],[IsGrandparentOfPatient],[IsFriendFamilyOfPatient],[IsCommiteeMember],[IsCampaignCabinet]
      , CASE WHEN [IsFormerTrustee]+[IsTrustee]+[IsChairsCouncil]+[IsParentofPatient]+[IsGrandparentOfPatient]+[IsFriendFamilyOfPatient]+[IsCommiteeMember]+[IsCampaignCabinet] > 0 THEN 1 ELSE 0 END AS [HasRelationship]
      into #CONSTITUENCY
	  FROM CTE
      WHERE ROWNUMBER = 1


--select count(*) from #Rel where #Rel.CONSTITUENTLOOKUPID='70434'

--------BU------------------------------------------------------------------
Print ('Creating Table BU')
IF OBJECT_ID('tempdb..#CONS_BU') IS NOT NULL DROP TABLE #CONS_BU ;
Select CONSTITUENT.CONSTITUENTLOOKUPID,BUSINESSUNIT
INTO #CONS_BU
FROM [ECSKF_RPT_BBDW].[BBDW].[DIM_APPEALBUSINESSUNIT_EXT] AS BUSINESS 
                  INNER JOIN [ECSKF_RPT_BBDW].[BBDW].[DIM_APPEAL] AS APPEAL
                        ON BUSINESS.[APPEALDIMID] = APPEAL.[APPEALDIMID]
                  INNER JOIN [ECSKF_RPT_BBDW].[BBDW]. [FACT_FINANCIALTRANSACTIONLINEITEM] AS REVENUE 
                        ON APPEAL.[APPEALDIMID] = REVENUE.[APPEALDIMID] 
                  INNER JOIN [ECSKF_RPT_BBDW].[BBDW].[DIM_CONSTITUENT] AS CONSTITUENT     
                        ON REVENUE.[CONSTITUENTDIMID] = CONSTITUENT.[CONSTITUENTDIMID]
                  INNER JOIN [ECSKF_RPT_BBDW].[BBDW].[DIM_REVENUECODE] AS CODES
                        ON CODES.[REVENUECODEDIMID] = REVENUE.[REVENUECODEDIMID]
where REVENUE.FINANCIALTRANSACTIONLINEITEMAMOUNT>0
and CONSTITUENTLOOKUPID <> '0'
and
((codes.REVENUETRANSACTIONTYPECODE = 0 and CODES.REVENUEAPPLICATIONCODE = 0) --donation
or (codes.REVENUETRANSACTIONTYPECODE = 0 and CODES.REVENUEAPPLICATIONCODE = 3)  -- Rec Gift payment
or (codes.REVENUETRANSACTIONTYPECODE = 0 and CODES.REVENUEAPPLICATIONCODE = 2)  -- Pledge Payment
)  
group by CONSTITUENT.CONSTITUENTLOOKUPID,BUSINESSUNIT

--select distinct(BUSINESSUNIT) from #CONS_BU

IF OBJECT_ID('tempdb..#CONS_BUni') IS NOT NULL DROP TABLE #CONS_BUni  --Remove dbo here 
select *
into #CONS_BUni
from  (select CONSTITUENTLOOKUPID,BUSINESSUNIT from #CONS_BU) as sourcetable
PIVOT 
(
 count(BUSINESSUNIT)
FOR BUSINESSUNIT IN ([Major Gifts],[SKF],[Corporate Partnerships],[Direct Marketing],[Events])
) as pivot_table
----Houshold----------------------------------------------------------------------
Print ('Creating Table Household')
IF OBJECT_ID('tempdb..#Household') IS NOT NULL DROP TABLE #Household;  --Remove dbo here 
WITH HouseholdCount AS
(
      SELECT HOUSEHOLDID, COUNT(*) AS HHCOUNT FROM [KYDSPRDDB30].[ECSKF].[dbo].[CONSTITUENTHOUSEHOLD]
            GROUP BY HOUSEHOLDID
)
, RELATIONS AS
(
      SELECT  FIRST_CONSTITUENT.CONSTITUENTDIMID,RELATIONSHIP_FLAGS.ISSPOUSE 
      FROM    [ECSKF_RPT_BBDW].[BBDW].[FACT_CONSTITUENTRELATIONSHIP] RELATIONSHIPS
                  INNER JOIN [ECSKF_RPT_BBDW].[BBDW].[DIM_CONSTITUENTRELATIONSHIPTYPE] RELATIONSHIP_TYPES 
                        ON RELATIONSHIP_TYPES.CONSTITUENTRELATIONSHIPTYPEDIMID = RELATIONSHIPS.CONSTITUENTRELATIONSHIPTYPEDIMID
                  INNER JOIN [ECSKF_RPT_BBDW].[BBDW].[DIM_CONSTITUENT] FIRST_CONSTITUENT 
                        ON FIRST_CONSTITUENT.CONSTITUENTDIMID = RELATIONSHIPS.CONSTITUENTDIMID
                  INNER JOIN [ECSKF_RPT_BBDW].[BBDW].[DIM_CONSTITUENTRELATIONSHIPFLAG] RELATIONSHIP_FLAGS 
                        ON RELATIONSHIP_FLAGS.CONSTITUENTRELATIONSHIPFLAGDIMID = RELATIONSHIPS.CONSTITUENTRELATIONSHIPFLAGDIMID
						where RELATIONSHIP_FLAGS.ISSPOUSE = 1
)
,RESULT AS
(
      SELECT CONSTITUENTS.CONSTITUENTDIMID, CONSTITUENTS.CONSTITUENTLOOKUPID
            , CASE
                  WHEN  HOUSEHOLDS.ID IS NULL THEN 0
                  ELSE   1
            END AS HasHousehold
            ,ISNULL(HouseholdCount.HHCOUNT,0) AS HouseholdCount
            ,ISNULL(RELATIONS.ISSPOUSE, 0) AS ISSPOUSE
            FROM [ECSKF_RPT_BBDW].[BBDW].[DIM_CONSTITUENT] AS CONSTITUENTS
                  LEFT JOIN [KYDSPRDDB30].[ECSKF].[dbo].[CONSTITUENTHOUSEHOLD] AS HOUSEHOLDS WITH (NOLOCK)
                        ON    HOUSEHOLDS.ID = CONSTITUENTS.CONSTITUENTSYSTEMID
                  LEFT JOIN HouseholdCount 
                        ON    HouseholdCount.HOUSEHOLDID = HOUSEHOLDS.HOUSEHOLDID
                  LEFT JOIN RELATIONS
                        ON RELATIONS.CONSTITUENTDIMID = CONSTITUENTS.CONSTITUENTDIMID
)SELECT CONSTITUENTDIMID, CONSTITUENTLOOKUPID, HasHousehold, HouseholdCount,ISSPOUSE
 into #Household
      FROM RESULT
EXCEPT 
 SELECT CONSTITUENTDIMID, CONSTITUENTLOOKUPID, HasHousehold, HouseholdCount,ISSPOUSE
      FROM RESULT 
      WHERE HasHousehold = 1 AND HouseholdCount = 0

---Relationsip--------------------------------------------------------------------------
Print ('Creating Table Relation')
IF OBJECT_ID('tempdb..#Relationsip') IS NOT NULL DROP TABLE #Relationsip  --Remove dbo here 
      SELECT  CONSTITUENTs.CONSTITUENTDIMID,CONSTITUENTs.CONSTITUENTLOOKUPID , count(*) as RelationshipCount
	  into #Relationsip
      FROM    [ECSKF_RPT_BBDW].[BBDW].[FACT_CONSTITUENTRELATIONSHIP] RELATIONSHIPS
                  INNER JOIN [ECSKF_RPT_BBDW].[BBDW].[DIM_CONSTITUENT] CONSTITUENTs 
                        ON CONSTITUENTs.CONSTITUENTDIMID = RELATIONSHIPS.CONSTITUENTDIMID
      GROUP BY    CONSTITUENTs.CONSTITUENTDIMID,CONSTITUENTs.CONSTITUENTLOOKUPID    
-----Interation -----------------------------------------------------------
Print ('Creating Table INTRACT')
IF OBJECT_ID('tempdb..#INTRACT') IS NOT NULL DROP TABLE #INTRACT  --Remove dbo here 
select *,0 as 'T_INTRACT'
into #INTRACT
from ( SELECT CO.CONSTITUENTDIMID,DI.InteractionType 
FROM  [ECSKF_RPT_BBDW].[BBDW].DIM_CONSTITUENT AS CO
inner join 
[ECSKF_RPT_BBDW].[BBDW].FACT_INTERACTION AS FI
ON CO.CONSTITUENTDIMID = FI.CONSTITUENTDIMID
inner JOIN [ECSKF_RPT_BBDW].[BBDW].DIM_INTERACTION AS DI
ON FI.INTERACTIONDIMID = DI.INTERACTIONDIMID
) as resurce_table
pivot 
(
count(InteractionType) for InteractionType in ([In Person],[Phone],[Email])
)  as pivottable

update #INTRACT set T_INTRACT=[In Person]+[Phone]+[Email] ;
--select * from #INTRACT
-----RG---------------------------------------------------------------------
Print ('Creating Table RG')
IF OBJECT_ID('tempdb..#RG') IS NOT NULL DROP TABLE #RG;  --Remove dbo here 
WITH RC_STATES AS 
 (
SELECT REVENUE.CONSTITUENTDIMID, RC_ATTRIBUTE.RevenueSysId
            --,DATENAME(MM,StartDATE)as TerminatinDate
            ,CASE
                  WHEN RC_ATTRIBUTE.Value LIKE 'Hold%' THEN 'Hold'
                  WHEN RC_ATTRIBUTE.Value LIKE '%Donor%' THEN 'Donor'
                  ELSE 'Terminated' 
            END AS [STATE]
            , ROW_NUMBER() OVER (PARTITION BY REVENUE.CONSTITUENTDIMID, RC_ATTRIBUTE.RevenueSysId ORDER BY RC_ATTRIBUTE.StartDATE DESC) AS ROW
      FROM [ECSKF_RPT_BBDW].[dbo].[SKF_RPT_Attributed_EXT] RC_ATTRIBUTE 
            INNER JOIN  [ECSKF_RPT_BBDW].BBDW.FACT_REVENUE AS REVENUE
                  ON REVENUE.REVENUESYSTEMID = RC_ATTRIBUTE.RevenueSysId
            INNER JOIN [ECSKF_RPT_BBDW].BBDW.DIM_REVENUECODE CODES 
                   ON REVENUE.REVENUECODEDIMID = CODES.REVENUECODEDIMID
      WHERE CODES.REVENUETRANSACTIONTYPECODE = 2 --and REVENUE.CONSTITUENTDIMID = '1537672'
)
, TERMINATED AS 
(
      SELECT CONSTITUENTDIMID, RevenueSysId,[STATE]
            FROM  RC_STATES
            WHERE ROW = 1
) 
, ALL_RC AS 
(
      SELECT REVENUE.CONSTITUENTDIMID, COUNT(REVENUE.CONSTITUENTDIMID) AS RC_COUNT
            FROM [ECSKF_RPT_BBDW].BBDW.FACT_FINANCIALTRANSACTION AS REVENUE
            INNER JOIN  [ECSKF_RPT_BBDW].BBDW.FACT_FINANCIALTRANSACTIONLINEITEM AS REVENUE_SPLIT
                  ON REVENUE.FINANCIALTRANSACTIONFACTID = REVENUE_SPLIT.FINANCIALTRANSACTIONFACTID
            INNER JOIN [ECSKF_RPT_BBDW].BBDW.DIM_REVENUECODE CODES 
                   ON REVENUE_SPLIT.REVENUECODEDIMID = CODES.REVENUECODEDIMID
            WHERE CODES.REVENUETRANSACTIONTYPECODE = 2 
            --AND REVENUE.CONSTITUENTDIMID = '1291049'      
            GROUP BY REVENUE.CONSTITUENTDIMID
)
SELECT DISTINCT CONSTITUENTS.CONSTITUENTDIMID, CONSTITUENTS.CONSTITUENTLOOKUPID,ALL_RC.RC_COUNT
            ,ALL_RC.RC_COUNT - ISNULL(
                  (SELECT COUNT(*) 
                        FROM TERMINATED AS T 
                        WHERE T.CONSTITUENTDIMID = CONSTITUENTS.CONSTITUENTDIMID --AND TERMINATED.ROW = 1      
            ),0)AS ACTIVE_COUNT
            ,(
                  SELECT COUNT(*) 
                        FROM TERMINATED AS T 
                        WHERE T.CONSTITUENTDIMID = CONSTITUENTS.CONSTITUENTDIMID AND T.[STATE] = 'Hold'
            )AS HOLD_COUNT
            ,(
                  SELECT COUNT(*) 
                        FROM TERMINATED AS T 
                        WHERE T.CONSTITUENTDIMID = CONSTITUENTS.CONSTITUENTDIMID AND T.[STATE] = 'Donor' 
            )AS DONOR_TERMINATED_COUNT
            ,(
                  SELECT COUNT(*) 
                        FROM TERMINATED AS T 
                        WHERE T.CONSTITUENTDIMID = CONSTITUENTS.CONSTITUENTDIMID AND T.[STATE] = 'Terminated'
            )AS SYSTEM_TERMINATED_COUNT         
      into #RG
	  FROM TERMINATED
            INNER JOIN [ECSKF_RPT_BBDW].BBDW.DIM_CONSTITUENT AS CONSTITUENTS
                  ON CONSTITUENTS.CONSTITUENTDIMID = TERMINATED.CONSTITUENTDIMID
            INNER JOIN ALL_RC 
                  ON ALL_RC.CONSTITUENTDIMID = CONSTITUENTS.CONSTITUENTDIMID
---- Opportunity ----------------------------------------------------------


select * from ( select c.CONSTITUENTDIMID,a.OPPORTUNITYSTATUS from 
[ECSKF_RPT_BBDW].[BBDW].DIM_CONSTITUENT as c
inner join 
[ECSKF_RPT_BBDW].[BBDW].FACT_OPPORTUNITY a
on a.CONSTITUENTDIMID=c.CONSTITUENTDIMID
inner join [ECSKF_RPT_BBDW].[BBDW].DIM_PROSPECTPLAN as b
on a.PROSPECTPLANDIMID=b.PROSPECTPLANDIMID
where OPPORTUNITYTYPE='Major Gifts'
) as resurce_table
pivot 
(
count(OPPORTUNITYSTATUS) for OPPORTUNITYSTATUS in (Unqualified,Qualified,[Response pending],Accepted,Canceled,Rejected)
)  as pivottable



-----MG---------------------------------------------------------------------
Print ('Creating Table MG')
IF OBJECT_ID('tempdb..#MG') IS NOT NULL DROP TABLE #MG  --Remove dbo here 
SELECT DT.FISCALYEAR,
	CO.CONSTITUENTLOOKUPID, 
	sum(REVENUE.FINANCIALTRANSACTIONLINEITEMAMOUNT) AS SUM_AMOUNT
     INTO #MG
     FROM  [ECSKF_RPT_BBDW].[BBDW].FACT_FINANCIALTRANSACTIONLINEITEM AS REVENUE
                  INNER JOIN  [ECSKF_RPT_BBDW].[BBDW].DIM_CONSTITUENT AS CO
                        ON CO.CONSTITUENTDIMID = REVENUE.CONSTITUENTDIMID
                  INNER JOIN  [ECSKF_RPT_BBDW].[BBDW].DIM_REVENUECODE AS CODES
                        ON CODES.REVENUECODEDIMID = REVENUE.REVENUECODEDIMID 
					inner join [ECSKF_RPT_BBDW].[BBDW].DIM_DATE DT
						ON   REVENUE.FINANCIALTRANSACTIONDATEDIMID= DT.DATEDIMID 
where 
(codes.REVENUETRANSACTIONTYPECODE = 0 and CODES.REVENUEAPPLICATIONCODE = 0) --Donation
or (codes.REVENUETRANSACTIONTYPECODE = 0 --payment
and (codes.REVENUETRANSACTIONTYPECODE = 1  --Pledge
or  codes.REVENUETRANSACTIONTYPECODE = 2   ))   --RG
--and co.CONSTITUENTLOOKUPID='174572'
group by CO.CONSTITUENTLOOKUPID,DT.FISCALYEAR
order by CO.CONSTITUENTLOOKUPID,DT.FISCALYEAR

IF OBJECT_ID('tempdb..#ISMG') IS NOT NULL DROP TABLE #ISMG  --Remove dbo here 
SELECT 	CONSTITUENTLOOKUPID, min(FISCALYEAR) as F_MGIFT_DATE, max(FISCALYEAR) as L_MGIFT_DATE,
	count(SUM_AMOUNT) as MGCOUNT, max(SUM_AMOUNT) as MGMAX 
     INTO #ISMG
     FROM  #MG
WHERE SUM_AMOUNT>9999
group by CONSTITUENTLOOKUPID

	  ----,CONSTITUENT.AGE-(2015-YEAR(REVENUE.FINANCIALTRANSACTIONDATE)) as AGEPAY

--select * from #MG where CONSTITUENTLOOKUPID='91792'
--select * from #ISMG where CONSTITUENTLOOKUPID='91792'


---------------------------------------------------------------------------
Print ('Joining')
IF OBJECT_ID('[ConversionMapping].[dbo].[saeed_Constituents]') IS NOT NULL DROP TABLE [ConversionMapping].[dbo].[saeed_Constituents]
Select 
#Bio.CONSTITUENTLOOKUPID,
#Bio.CONSTITUENTDIMID,
#Bio.[AGE],
#Bio.[TITLE],
#Bio.[GENDER],
#Bio.[DONOTMAIL]
,#Bio.[GIVESANONYMOUSLY]
,#Bio.[ISACTIVE]
--,#Bio.[ISCONSTITUENT]
,#Bio.[ISDECEASED]
--,#Bio.[ISGROUP]
--,#Bio.[ISORGANIZATION]
,#Bio.[ISNETCOMMUNITYMEMBER]
,#Bio.[ISACTIVEBOARDMEMBER]
,#Bio.[ISACTIVECOMMITTEE]
,#Bio.[ISACTIVEFUNDRAISER]
,#Bio.[ISACTIVEPROSPECT]
,#Bio.[ISACTIVESTAFF]
--,#Bio.[ISACTIVESPONSOR]
,#Bio.[ISACTIVEVOLUNTEER]
,#Bio.MARITALSTATUS
,#AddDet.[PRIMARYADDRESSCITY]
,#AddDet.[PRIMARYADDRESSSTATE]
,#AddDet.[ISCONFIDENTIAL]
,#AddDet.Home
,#AddDet.Business
,#AddDet.FSA
,#AddDet.Longitude
,#AddDet.Latitude
,#intr.Interest
,isnull(#APPEAL.APEAL_COUNT,0) as APEAL_COUNT
,isnull(#APPEAL.APEAL_COUNT_CP,0) as APEAL_COUNT_CP
,isnull(#APPEAL.APEAL_COUNT_DM,0) as APEAL_COUNT_DM
,isnull(#APPEAL.APEAL_COUNT_DTD,0) as APEAL_COUNT_DTD
,isnull(#APPEAL.APEAL_COUNT_GenDon,0) as APEAL_COUNT_GenDon
,isnull(#APPEAL.APEAL_COUNT_lotry,0) as APEAL_COUNT_lotry
,isnull(#REVEN1.H_PG,0) as H_PG
,isnull(#REVEN1.H_PLG,0) as H_PLG
,isnull(#REVEN1.H_RG,0) as H_RG
,isnull(#REVEN1.P_DON,0) as P_DON
,isnull(#REVEN1.P_PLG,0) as P_PLG
,isnull(#REVEN1.P_RG,0) as P_RG
,isnull(#REVEN1.T_REV,0) as T_REV
,#REVEN2.GFT_TCOUNT
,#REVEN2.FIRST_REV_DATE
,#REVEN2.LAST_REV_DATE
,isnull(#REVEN2.PAYLENGTH,0) as PAYLENGTH
,#CONSTITUENCY.IsCampaignCabinet
,#CONSTITUENCY.IsChairsCouncil
,#CONSTITUENCY.[IsCommiteeMember]
,#CONSTITUENCY.IsFormerTrustee
,#CONSTITUENCY.IsFriendFamilyOfPatient
,#CONSTITUENCY.IsGrandparentOfPatient
,#CONSTITUENCY.IsParentofPatient
,isnull(#CONS_BUni.[Corporate Partnerships],0) as [Corporate Partnerships]
,isnull(#CONS_BUni.[Direct Marketing],0) as [Direct Marketing]
,isnull(#CONS_BUni.[Events],0) as [Events]
,isnull(#CONS_BUni.[Major Gifts],0) as [Major Gifts]
,isnull(#CONS_BUni.SKF,0) as SKF
,isnull(#AFF.AFFLUENCEINDICATORNUMBER,0) as AFFLUENCEINDICATORNUMBER
,isnull(#AFF.AFFLUENCEINDICATORASSETS,0) as AFFLUENCEINDICATORASSETS
,isnull(#AFF.BIOGRAPHICALNUMBER,0) as BIOGRAPHICALNUMBER
,#AFF.BUSINESSOWNERSHIPASSETS
,#AFF.BUSINESSOWNERSHIPNUMBER
,#AFF.NONPROFITAFFILIATIONNUMBER
,#AFF.PHILANTHROPICGIFTNUMBER
,#AFF.REALESTATENUMBER
,#Household.HasHousehold
,#Household.HouseholdCount
,#Household.ISSPOUSE
,#Relationsip.RelationshipCount
,isnull(#INTRACT.Email,0) as Email
,isnull(#INTRACT.[In Person],0) as [In Person]
,isnull(#INTRACT.Phone,0) as Phone
,isnull(#INTRACT.T_INTRACT,0) as T_INTRACT
,isnull(#RG.ACTIVE_COUNT,0) as RG_ACTIVE_COUNT
,isnull(#RG.RC_COUNT,0) as RC_COUNT
,isnull(#RG.HOLD_COUNT,0) as HOLD_COUNT
,isnull(#RG.DONOR_TERMINATED_COUNT,0) as DONOR_TERMINATED_COUNT
,isnull(#RG.SYSTEM_TERMINATED_COUNT,0) as SYSTEM_TERMINATED_COUNT
,isnull(#ISMG.MGCOUNT,0) MGCOUNT
,isnull(#ISMG.MGMAX,0) as MGMAX
,CASE WHEN ISNUMERIC(#ISMG.MGCOUNT)>0 THEN 'Yes' ELSE 'No' END as ISMG
into  [ConversionMapping].[dbo].[saeed_Constituents]
from #Bio
left outer join #AddDet
on #Bio.CONSTITUENTDIMID=#AddDet.CONSTITUENTDIMID
Left outer join #intr
on #Bio.CONSTITUENTLOOKUPID=#intr.CONSTITUENTLOOKUPID
Left outer join #APPEAL
on #Bio.CONSTITUENTDIMID=#APPEAL.CONSTITUENTDIMID
Left outer join #REVEN1
on #Bio.CONSTITUENTLOOKUPID=#REVEN1.CONSTITUENTLOOKUPID
Left outer join #REVEN2
on #Bio.CONSTITUENTLOOKUPID=#REVEN2.CONSTITUENTLOOKUPID
Left outer join #CONSTITUENCY
on #Bio.CONSTITUENTLOOKUPID=#CONSTITUENCY.CONSTITUENTLOOKUPID
left outer join #CONS_BUni
on #Bio.CONSTITUENTLOOKUPID=#CONS_BUni.CONSTITUENTLOOKUPID
left outer join #AFF
on #Bio.CONSTITUENTLOOKUPID = #AFF.CONSTITUENTLOOKUPID
left outer join #Household
on #Bio.CONSTITUENTLOOKUPID= #Household.CONSTITUENTLOOKUPID
left outer join #Relationsip
on #Bio.CONSTITUENTLOOKUPID =#Relationsip.CONSTITUENTLOOKUPID
left outer join #INTRACT
on #Bio.CONSTITUENTDIMID=#INTRACT.CONSTITUENTDIMID
left outer join #ISMG
on #Bio.CONSTITUENTLOOKUPID= #ISMG.CONSTITUENTLOOKUPID
left outer join #RG
on #Bio.CONSTITUENTLOOKUPID=#RG.CONSTITUENTLOOKUPID
where -- FIRST_REV_DATE>'1990-01-01' and FIRST_REV_DATE<'2015-06-01' and 
LAST_REV_DATE>'2000-01-01' and LAST_REV_DATE<'2015-06-01'


update  [ConversionMapping].[dbo].[saeed_Constituents]
set age=null where age<10 or age>100

--------------------------------------------------------------------
select distinct(AFFLUENCEINDICATORNUMBER) from [ConversionMapping].[dbo].[saeed_Constituents]
select distinct(DONOR_TERMINATED_COUNT) from [ConversionMapping].[dbo].[saeed_Constituents]



select * from [ConversionMapping].[dbo].[saeed_Constituents]
where CONSTITUENTLOOKUPID='299335'

select count(*) from [ConversionMapping].[dbo].[saeed_Constituents]
where CONSTITUENTLOOKUPID='70434'




select CONSTITUENTLOOKUPID,count(CONSTITUENTLOOKUPID) from [ConversionMapping].[dbo].[saeed_Constituents]
group by CONSTITUENTLOOKUPID
having count(CONSTITUENTLOOKUPID)>1
----------------------------------------------------


