--sample constituent lookup id =174572

drop table #1
drop table #2

-- payments
SELECT 
ROW_NUMBER() OVER( ORDER BY CONSTITUENTLOOKUPID,FINANCIALTRANSACTIONDATE ) AS rown,
CONVERT(DATE,REVENUE.FINANCIALTRANSACTIONDATE) AS INTERACTION_DATE,CO.CONSTITUENTLOOKUPID, CODES.REVENUETRANSACTIONTYPE AS ACTION_TYPE 
                  ,REVENUE.FINANCIALTRANSACTIONLINEITEMAMOUNT AS AMOUNT, CODES.REVENUEAPPLICATION AS APPLICATION_TYPE
				 ,codes.REVENUETRANSACTIONTYPECODE, CODES.REVENUEAPPLICATIONTYPECODE
    INTO #1
            FROM BBDW.FACT_FINANCIALTRANSACTIONLINEITEM AS REVENUE
                  INNER JOIN BBDW.DIM_CONSTITUENT AS CO
                        ON CO.CONSTITUENTDIMID = REVENUE.CONSTITUENTDIMID
                  INNER JOIN BBDW.DIM_REVENUECODE AS CODES
                        ON CODES.REVENUECODEDIMID = REVENUE.REVENUECODEDIMID 
where ((codes.REVENUETRANSACTIONTYPECODE = 0 and CODES.REVENUEAPPLICATIONCODE = 0) 
or (codes.REVENUETRANSACTIONTYPECODE = 1 or  codes.REVENUETRANSACTIONTYPECODE = 2 or codes.REVENUETRANSACTIONTYPECODE = 3 ))
--and CONSTITUENTLOOKUPID='8-12085473'
order by CONSTITUENTLOOKUPID,INTERACTION_DATE


----------------------- To add row number
SELECT 
 (ROW_NUMBER() OVER( ORDER BY CONSTITUENTLOOKUPID,rown )) -
 (ROW_NUMBER() OVER( PARTITION BY CONSTITUENTLOOKUPID,ACTION_TYPE ORDER BY CONSTITUENTLOOKUPID,rown )) as grp,
*
into #2
FROM #1 
        WHERE CONSTITUENTLOOKUPID <> '0'
        ORDER BY CONSTITUENTLOOKUPID

------------------------ To group by only rows which are sequencial

With T as ( 

 select * from #2

) SELECT CONSTITUENTLOOKUPID,ACTION_TYPE, COUNT(*) act_count
FROM   T
GROUP  BY CONSTITUENTLOOKUPID,ACTION_TYPE, grp 
ORDER BY MIN(rown)



-------------------- To add seq number to dataset

SELECT 
ROW_NUMBER() OVER( ORDER BY CONSTITUENTLOOKUPID,INTERACTION_DATE ) AS row,  
ROW_NUMBER() OVER(PARTITION BY constituentlookupid ORDER BY INTERACTION_DATE ) AS seq, 
*
into [ConversionMapping].[dbo].[saeed_donation_states]
FROM #1 
        ORDER BY CONSTITUENTLOOKUPID


select top 1000 * from [ConversionMapping].[dbo].[saeed_donation_states]
order by CONSTITUENTLOOKUPID,INTERACTION_DATE